// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAnnouncement = "announcements"

// Announcement mapped from table <announcements>
type Announcement struct {
	ID        string         `gorm:"column:id;primaryKey" json:"id"`
	Title     string         `gorm:"column:title;not null" json:"title"`
	Content   string         `gorm:"column:content;not null" json:"content"`
	CreatedBy string         `gorm:"column:created_by;not null" json:"created_by"`
	IsPinned  bool           `gorm:"column:is_pinned;not null" json:"is_pinned"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Announcement's table name
func (*Announcement) TableName() string {
	return TableNameAnnouncement
}
