// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameApplication = "applications"

// Application Table to store third-party application information. Type: master
type Application struct {
	ID               string         `gorm:"column:id;primaryKey" json:"id"`
	Name             string         `gorm:"column:name;not null" json:"name"`
	Description      string         `gorm:"column:description" json:"description"`
	WebsiteURL       string         `gorm:"column:website_url" json:"website_url"`
	PrivacyPolicyURL string         `gorm:"column:privacy_policy_url" json:"privacy_policy_url"`
	ClientSecret     string         `gorm:"column:client_secret;not null" json:"client_secret"`
	UserID           string         `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt        time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Application's table name
func (*Application) TableName() string {
	return TableNameApplication
}
