// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuditLog = "audit_logs"

// AuditLog Table to store audit logs for security and compliance. Type: transactional
type AuditLog struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	UserID         *string   `gorm:"column:user_id" json:"user_id"`
	ApplicationID  *string   `gorm:"column:application_id" json:"application_id"`
	SessionID      *string   `gorm:"column:session_id;comment:If author is application, this links to the jti" json:"session_id"` // If author is application, this links to the jti
	Action         string    `gorm:"column:action;not null" json:"action"`
	TargetResource string    `gorm:"column:target_resource;not null" json:"target_resource"`
	Trusted        bool      `gorm:"column:trusted;not null" json:"trusted"`
	Details        *string   `gorm:"column:details" json:"details"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName AuditLog's table name
func (*AuditLog) TableName() string {
	return TableNameAuditLog
}
