// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthorizationRequest = "authorization_requests"

// AuthorizationRequest Table to store OAuth2 authorization requests. Type: transactional
type AuthorizationRequest struct {
	ID                  string    `gorm:"column:id;primaryKey" json:"id"`
	SessionID           string    `gorm:"column:session_id;not null" json:"session_id"`
	ApplicationID       string    `gorm:"column:application_id;not null" json:"application_id"`
	Scope               string    `gorm:"column:scope;not null" json:"scope"`
	RedirectURI         string    `gorm:"column:redirect_uri;not null" json:"redirect_uri"`
	State               string    `gorm:"column:state" json:"state"`
	Nonce               string    `gorm:"column:nonce" json:"nonce"`
	CodeChallenge       string    `gorm:"column:code_challenge" json:"code_challenge"`
	CodeChallengeMethod string    `gorm:"column:code_challenge_method" json:"code_challenge_method"`
	ResponseType        string    `gorm:"column:response_type;not null;default:code" json:"response_type"`
	Code                string    `gorm:"column:code" json:"code"`
	IsEnabled           bool      `gorm:"column:is_enabled;not null" json:"is_enabled"`
	ExpiresAt           time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
	CreatedAt           time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName AuthorizationRequest's table name
func (*AuthorizationRequest) TableName() string {
	return TableNameAuthorizationRequest
}
