// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameConsent = "consents"

// Consent Table to store user consents for third-party applications. Type: master
type Consent struct {
	ID            string         `gorm:"column:id;primaryKey" json:"id"`
	UserID        string         `gorm:"column:user_id;not null" json:"user_id"`
	ApplicationID string         `gorm:"column:application_id;not null" json:"application_id"`
	Scope         string         `gorm:"column:scope;not null" json:"scope"`
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Consent's table name
func (*Consent) TableName() string {
	return TableNameConsent
}
