// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmailVerificationCode = "email_verification_codes"

// EmailVerificationCode Table to store email verification codes. Type: transactional
type EmailVerificationCode struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	UserID      string    `gorm:"column:user_id;not null" json:"user_id"`
	Code        string    `gorm:"column:code;not null" json:"code"`
	ExpiresAt   time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
	RequestType string    `gorm:"column:request_type;not null" json:"request_type"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName EmailVerificationCode's table name
func (*EmailVerificationCode) TableName() string {
	return TableNameEmailVerificationCode
}
