// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExternalIdentity = "external_identities"

// ExternalIdentity Table to store external identity links for users. Type: master
type ExternalIdentity struct {
	ID             string         `gorm:"column:id;primaryKey" json:"id"`
	UserID         string         `gorm:"column:user_id;not null" json:"user_id"`
	Provider       string         `gorm:"column:provider;not null" json:"provider"`
	ExternalUserID string         `gorm:"column:external_user_id;not null" json:"external_user_id"`
	IDToken        string         `gorm:"column:id_token;not null" json:"id_token"`
	AccessToken    string         `gorm:"column:access_token;not null" json:"access_token"`
	RefreshToken   string         `gorm:"column:refresh_token" json:"refresh_token"`
	TokenExpiresAt time.Time      `gorm:"column:token_expires_at" json:"token_expires_at"`
	CreatedAt      time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName ExternalIdentity's table name
func (*ExternalIdentity) TableName() string {
	return TableNameExternalIdentity
}
