// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRedirectURI = "redirect_uris"

// RedirectURI Table to store redirect URIs for third-party applications. Type: master
type RedirectURI struct {
	ApplicationID string         `gorm:"column:application_id;not null" json:"application_id"`
	URI           string         `gorm:"column:uri;not null" json:"uri"`
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName RedirectURI's table name
func (*RedirectURI) TableName() string {
	return TableNameRedirectURI
}
