// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSession = "sessions"

// Session Table to store user sessions. Type: master
type Session struct {
	ID          string         `gorm:"column:id;primaryKey" json:"id"`
	UserID      string         `gorm:"column:user_id;not null" json:"user_id"`
	IPAddress   string         `gorm:"column:ip_address" json:"ip_address"`
	UserAgent   string         `gorm:"column:user_agent" json:"user_agent"`
	ExpiresAt   time.Time      `gorm:"column:expires_at;not null" json:"expires_at"`
	LastLoginAt time.Time      `gorm:"column:last_login_at;not null" json:"last_login_at"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
