// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User Table to store user credential information. Type: master
type User struct {
	ID                string         `gorm:"column:id;primaryKey" json:"id"`
	CustomID          string         `gorm:"column:custom_id;not null" json:"custom_id"`
	Email             string         `gorm:"column:email;not null" json:"email"`
	ExternalEmail     string         `gorm:"column:external_email;not null" json:"external_email"`
	EmailVerified     bool           `gorm:"column:email_verified;not null" json:"email_verified"`
	AffiliationPeriod string         `gorm:"column:affiliation_period" json:"affiliation_period"`
	PasswordHash      string         `gorm:"column:password_hash;not null" json:"password_hash"`
	Status            string         `gorm:"column:status;not null;default:established" json:"status"`
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	TotpSecret        string         `gorm:"column:totp_secret" json:"totp_secret"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
