// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/UniPro-tech/UniQUE-Auth/internal/model"
)

func newAuthorizationRequest(db *gorm.DB, opts ...gen.DOOption) authorizationRequest {
	_authorizationRequest := authorizationRequest{}

	_authorizationRequest.authorizationRequestDo.UseDB(db, opts...)
	_authorizationRequest.authorizationRequestDo.UseModel(&model.AuthorizationRequest{})

	tableName := _authorizationRequest.authorizationRequestDo.TableName()
	_authorizationRequest.ALL = field.NewAsterisk(tableName)
	_authorizationRequest.ID = field.NewString(tableName, "id")
	_authorizationRequest.UserID = field.NewString(tableName, "user_id")
	_authorizationRequest.ApplicationID = field.NewString(tableName, "application_id")
	_authorizationRequest.Scope = field.NewString(tableName, "scope")
	_authorizationRequest.RedirectURI = field.NewString(tableName, "redirect_uri")
	_authorizationRequest.State = field.NewString(tableName, "state")
	_authorizationRequest.Nonce = field.NewString(tableName, "nonce")
	_authorizationRequest.CodeChallenge = field.NewString(tableName, "code_challenge")
	_authorizationRequest.CodeChallengeMethod = field.NewString(tableName, "code_challenge_method")
	_authorizationRequest.Code = field.NewString(tableName, "code")
	_authorizationRequest.IsEnabled = field.NewBool(tableName, "is_enabled")
	_authorizationRequest.ExpiresAt = field.NewTime(tableName, "expires_at")
	_authorizationRequest.CreatedAt = field.NewTime(tableName, "created_at")

	_authorizationRequest.fillFieldMap()

	return _authorizationRequest
}

// authorizationRequest Table to store OAuth2 authorization requests. Type: transactional
type authorizationRequest struct {
	authorizationRequestDo

	ALL                 field.Asterisk
	ID                  field.String
	UserID              field.String
	ApplicationID       field.String
	Scope               field.String
	RedirectURI         field.String
	State               field.String
	Nonce               field.String
	CodeChallenge       field.String
	CodeChallengeMethod field.String
	Code                field.String
	IsEnabled           field.Bool
	ExpiresAt           field.Time
	CreatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (a authorizationRequest) Table(newTableName string) *authorizationRequest {
	a.authorizationRequestDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authorizationRequest) As(alias string) *authorizationRequest {
	a.authorizationRequestDo.DO = *(a.authorizationRequestDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authorizationRequest) updateTableName(table string) *authorizationRequest {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.UserID = field.NewString(table, "user_id")
	a.ApplicationID = field.NewString(table, "application_id")
	a.Scope = field.NewString(table, "scope")
	a.RedirectURI = field.NewString(table, "redirect_uri")
	a.State = field.NewString(table, "state")
	a.Nonce = field.NewString(table, "nonce")
	a.CodeChallenge = field.NewString(table, "code_challenge")
	a.CodeChallengeMethod = field.NewString(table, "code_challenge_method")
	a.Code = field.NewString(table, "code")
	a.IsEnabled = field.NewBool(table, "is_enabled")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *authorizationRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authorizationRequest) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["application_id"] = a.ApplicationID
	a.fieldMap["scope"] = a.Scope
	a.fieldMap["redirect_uri"] = a.RedirectURI
	a.fieldMap["state"] = a.State
	a.fieldMap["nonce"] = a.Nonce
	a.fieldMap["code_challenge"] = a.CodeChallenge
	a.fieldMap["code_challenge_method"] = a.CodeChallengeMethod
	a.fieldMap["code"] = a.Code
	a.fieldMap["is_enabled"] = a.IsEnabled
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a authorizationRequest) clone(db *gorm.DB) authorizationRequest {
	a.authorizationRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authorizationRequest) replaceDB(db *gorm.DB) authorizationRequest {
	a.authorizationRequestDo.ReplaceDB(db)
	return a
}

type authorizationRequestDo struct{ gen.DO }

type IAuthorizationRequestDo interface {
	gen.SubQuery
	Debug() IAuthorizationRequestDo
	WithContext(ctx context.Context) IAuthorizationRequestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAuthorizationRequestDo
	WriteDB() IAuthorizationRequestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAuthorizationRequestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAuthorizationRequestDo
	Not(conds ...gen.Condition) IAuthorizationRequestDo
	Or(conds ...gen.Condition) IAuthorizationRequestDo
	Select(conds ...field.Expr) IAuthorizationRequestDo
	Where(conds ...gen.Condition) IAuthorizationRequestDo
	Order(conds ...field.Expr) IAuthorizationRequestDo
	Distinct(cols ...field.Expr) IAuthorizationRequestDo
	Omit(cols ...field.Expr) IAuthorizationRequestDo
	Join(table schema.Tabler, on ...field.Expr) IAuthorizationRequestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAuthorizationRequestDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAuthorizationRequestDo
	Group(cols ...field.Expr) IAuthorizationRequestDo
	Having(conds ...gen.Condition) IAuthorizationRequestDo
	Limit(limit int) IAuthorizationRequestDo
	Offset(offset int) IAuthorizationRequestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthorizationRequestDo
	Unscoped() IAuthorizationRequestDo
	Create(values ...*model.AuthorizationRequest) error
	CreateInBatches(values []*model.AuthorizationRequest, batchSize int) error
	Save(values ...*model.AuthorizationRequest) error
	First() (*model.AuthorizationRequest, error)
	Take() (*model.AuthorizationRequest, error)
	Last() (*model.AuthorizationRequest, error)
	Find() ([]*model.AuthorizationRequest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthorizationRequest, err error)
	FindInBatches(result *[]*model.AuthorizationRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AuthorizationRequest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAuthorizationRequestDo
	Assign(attrs ...field.AssignExpr) IAuthorizationRequestDo
	Joins(fields ...field.RelationField) IAuthorizationRequestDo
	Preload(fields ...field.RelationField) IAuthorizationRequestDo
	FirstOrInit() (*model.AuthorizationRequest, error)
	FirstOrCreate() (*model.AuthorizationRequest, error)
	FindByPage(offset int, limit int) (result []*model.AuthorizationRequest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAuthorizationRequestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a authorizationRequestDo) Debug() IAuthorizationRequestDo {
	return a.withDO(a.DO.Debug())
}

func (a authorizationRequestDo) WithContext(ctx context.Context) IAuthorizationRequestDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authorizationRequestDo) ReadDB() IAuthorizationRequestDo {
	return a.Clauses(dbresolver.Read)
}

func (a authorizationRequestDo) WriteDB() IAuthorizationRequestDo {
	return a.Clauses(dbresolver.Write)
}

func (a authorizationRequestDo) Session(config *gorm.Session) IAuthorizationRequestDo {
	return a.withDO(a.DO.Session(config))
}

func (a authorizationRequestDo) Clauses(conds ...clause.Expression) IAuthorizationRequestDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authorizationRequestDo) Returning(value interface{}, columns ...string) IAuthorizationRequestDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authorizationRequestDo) Not(conds ...gen.Condition) IAuthorizationRequestDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authorizationRequestDo) Or(conds ...gen.Condition) IAuthorizationRequestDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authorizationRequestDo) Select(conds ...field.Expr) IAuthorizationRequestDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authorizationRequestDo) Where(conds ...gen.Condition) IAuthorizationRequestDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authorizationRequestDo) Order(conds ...field.Expr) IAuthorizationRequestDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authorizationRequestDo) Distinct(cols ...field.Expr) IAuthorizationRequestDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authorizationRequestDo) Omit(cols ...field.Expr) IAuthorizationRequestDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authorizationRequestDo) Join(table schema.Tabler, on ...field.Expr) IAuthorizationRequestDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authorizationRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAuthorizationRequestDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authorizationRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) IAuthorizationRequestDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authorizationRequestDo) Group(cols ...field.Expr) IAuthorizationRequestDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authorizationRequestDo) Having(conds ...gen.Condition) IAuthorizationRequestDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authorizationRequestDo) Limit(limit int) IAuthorizationRequestDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authorizationRequestDo) Offset(offset int) IAuthorizationRequestDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authorizationRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthorizationRequestDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authorizationRequestDo) Unscoped() IAuthorizationRequestDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authorizationRequestDo) Create(values ...*model.AuthorizationRequest) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authorizationRequestDo) CreateInBatches(values []*model.AuthorizationRequest, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authorizationRequestDo) Save(values ...*model.AuthorizationRequest) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authorizationRequestDo) First() (*model.AuthorizationRequest, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthorizationRequest), nil
	}
}

func (a authorizationRequestDo) Take() (*model.AuthorizationRequest, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthorizationRequest), nil
	}
}

func (a authorizationRequestDo) Last() (*model.AuthorizationRequest, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthorizationRequest), nil
	}
}

func (a authorizationRequestDo) Find() ([]*model.AuthorizationRequest, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthorizationRequest), err
}

func (a authorizationRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthorizationRequest, err error) {
	buf := make([]*model.AuthorizationRequest, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authorizationRequestDo) FindInBatches(result *[]*model.AuthorizationRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authorizationRequestDo) Attrs(attrs ...field.AssignExpr) IAuthorizationRequestDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authorizationRequestDo) Assign(attrs ...field.AssignExpr) IAuthorizationRequestDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authorizationRequestDo) Joins(fields ...field.RelationField) IAuthorizationRequestDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authorizationRequestDo) Preload(fields ...field.RelationField) IAuthorizationRequestDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authorizationRequestDo) FirstOrInit() (*model.AuthorizationRequest, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthorizationRequest), nil
	}
}

func (a authorizationRequestDo) FirstOrCreate() (*model.AuthorizationRequest, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthorizationRequest), nil
	}
}

func (a authorizationRequestDo) FindByPage(offset int, limit int) (result []*model.AuthorizationRequest, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authorizationRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authorizationRequestDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authorizationRequestDo) Delete(models ...*model.AuthorizationRequest) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authorizationRequestDo) withDO(do gen.Dao) *authorizationRequestDo {
	a.DO = *do.(*gen.DO)
	return a
}
