// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/UniPro-tech/UniQUE-Auth/internal/model"
)

func newConsent(db *gorm.DB, opts ...gen.DOOption) consent {
	_consent := consent{}

	_consent.consentDo.UseDB(db, opts...)
	_consent.consentDo.UseModel(&model.Consent{})

	tableName := _consent.consentDo.TableName()
	_consent.ALL = field.NewAsterisk(tableName)
	_consent.ID = field.NewString(tableName, "id")
	_consent.UserID = field.NewString(tableName, "user_id")
	_consent.ApplicationID = field.NewString(tableName, "application_id")
	_consent.Scope = field.NewString(tableName, "scope")
	_consent.CreatedAt = field.NewTime(tableName, "created_at")
	_consent.UpdatedAt = field.NewTime(tableName, "updated_at")
	_consent.DeletedAt = field.NewField(tableName, "deleted_at")

	_consent.fillFieldMap()

	return _consent
}

// consent Table to store user consents for third-party applications. Type: master
type consent struct {
	consentDo consentDo

	ALL           field.Asterisk
	ID            field.String
	UserID        field.String
	ApplicationID field.String
	Scope         field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field

	fieldMap map[string]field.Expr
}

func (c consent) Table(newTableName string) *consent {
	c.consentDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c consent) As(alias string) *consent {
	c.consentDo.DO = *(c.consentDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *consent) updateTableName(table string) *consent {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.UserID = field.NewString(table, "user_id")
	c.ApplicationID = field.NewString(table, "application_id")
	c.Scope = field.NewString(table, "scope")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *consent) WithContext(ctx context.Context) IConsentDo { return c.consentDo.WithContext(ctx) }

func (c consent) TableName() string { return c.consentDo.TableName() }

func (c consent) Alias() string { return c.consentDo.Alias() }

func (c consent) Columns(cols ...field.Expr) gen.Columns { return c.consentDo.Columns(cols...) }

func (c *consent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *consent) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["application_id"] = c.ApplicationID
	c.fieldMap["scope"] = c.Scope
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c consent) clone(db *gorm.DB) consent {
	c.consentDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c consent) replaceDB(db *gorm.DB) consent {
	c.consentDo.ReplaceDB(db)
	return c
}

type consentDo struct{ gen.DO }

type IConsentDo interface {
	gen.SubQuery
	Debug() IConsentDo
	WithContext(ctx context.Context) IConsentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConsentDo
	WriteDB() IConsentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConsentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConsentDo
	Not(conds ...gen.Condition) IConsentDo
	Or(conds ...gen.Condition) IConsentDo
	Select(conds ...field.Expr) IConsentDo
	Where(conds ...gen.Condition) IConsentDo
	Order(conds ...field.Expr) IConsentDo
	Distinct(cols ...field.Expr) IConsentDo
	Omit(cols ...field.Expr) IConsentDo
	Join(table schema.Tabler, on ...field.Expr) IConsentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConsentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConsentDo
	Group(cols ...field.Expr) IConsentDo
	Having(conds ...gen.Condition) IConsentDo
	Limit(limit int) IConsentDo
	Offset(offset int) IConsentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConsentDo
	Unscoped() IConsentDo
	Create(values ...*model.Consent) error
	CreateInBatches(values []*model.Consent, batchSize int) error
	Save(values ...*model.Consent) error
	First() (*model.Consent, error)
	Take() (*model.Consent, error)
	Last() (*model.Consent, error)
	Find() ([]*model.Consent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Consent, err error)
	FindInBatches(result *[]*model.Consent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Consent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConsentDo
	Assign(attrs ...field.AssignExpr) IConsentDo
	Joins(fields ...field.RelationField) IConsentDo
	Preload(fields ...field.RelationField) IConsentDo
	FirstOrInit() (*model.Consent, error)
	FirstOrCreate() (*model.Consent, error)
	FindByPage(offset int, limit int) (result []*model.Consent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConsentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c consentDo) Debug() IConsentDo {
	return c.withDO(c.DO.Debug())
}

func (c consentDo) WithContext(ctx context.Context) IConsentDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c consentDo) ReadDB() IConsentDo {
	return c.Clauses(dbresolver.Read)
}

func (c consentDo) WriteDB() IConsentDo {
	return c.Clauses(dbresolver.Write)
}

func (c consentDo) Session(config *gorm.Session) IConsentDo {
	return c.withDO(c.DO.Session(config))
}

func (c consentDo) Clauses(conds ...clause.Expression) IConsentDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c consentDo) Returning(value interface{}, columns ...string) IConsentDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c consentDo) Not(conds ...gen.Condition) IConsentDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c consentDo) Or(conds ...gen.Condition) IConsentDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c consentDo) Select(conds ...field.Expr) IConsentDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c consentDo) Where(conds ...gen.Condition) IConsentDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c consentDo) Order(conds ...field.Expr) IConsentDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c consentDo) Distinct(cols ...field.Expr) IConsentDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c consentDo) Omit(cols ...field.Expr) IConsentDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c consentDo) Join(table schema.Tabler, on ...field.Expr) IConsentDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c consentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConsentDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c consentDo) RightJoin(table schema.Tabler, on ...field.Expr) IConsentDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c consentDo) Group(cols ...field.Expr) IConsentDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c consentDo) Having(conds ...gen.Condition) IConsentDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c consentDo) Limit(limit int) IConsentDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c consentDo) Offset(offset int) IConsentDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c consentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConsentDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c consentDo) Unscoped() IConsentDo {
	return c.withDO(c.DO.Unscoped())
}

func (c consentDo) Create(values ...*model.Consent) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c consentDo) CreateInBatches(values []*model.Consent, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c consentDo) Save(values ...*model.Consent) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c consentDo) First() (*model.Consent, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consent), nil
	}
}

func (c consentDo) Take() (*model.Consent, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consent), nil
	}
}

func (c consentDo) Last() (*model.Consent, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consent), nil
	}
}

func (c consentDo) Find() ([]*model.Consent, error) {
	result, err := c.DO.Find()
	return result.([]*model.Consent), err
}

func (c consentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Consent, err error) {
	buf := make([]*model.Consent, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c consentDo) FindInBatches(result *[]*model.Consent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c consentDo) Attrs(attrs ...field.AssignExpr) IConsentDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c consentDo) Assign(attrs ...field.AssignExpr) IConsentDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c consentDo) Joins(fields ...field.RelationField) IConsentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c consentDo) Preload(fields ...field.RelationField) IConsentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c consentDo) FirstOrInit() (*model.Consent, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consent), nil
	}
}

func (c consentDo) FirstOrCreate() (*model.Consent, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consent), nil
	}
}

func (c consentDo) FindByPage(offset int, limit int) (result []*model.Consent, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c consentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c consentDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c consentDo) Delete(models ...*model.Consent) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *consentDo) withDO(do gen.Dao) *consentDo {
	c.DO = *do.(*gen.DO)
	return c
}
