// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/UniPro-tech/UniQUE-Auth/internal/model"
)

func newEmailVerificationCode(db *gorm.DB, opts ...gen.DOOption) emailVerificationCode {
	_emailVerificationCode := emailVerificationCode{}

	_emailVerificationCode.emailVerificationCodeDo.UseDB(db, opts...)
	_emailVerificationCode.emailVerificationCodeDo.UseModel(&model.EmailVerificationCode{})

	tableName := _emailVerificationCode.emailVerificationCodeDo.TableName()
	_emailVerificationCode.ALL = field.NewAsterisk(tableName)
	_emailVerificationCode.ID = field.NewString(tableName, "id")
	_emailVerificationCode.UserID = field.NewString(tableName, "user_id")
	_emailVerificationCode.Code = field.NewString(tableName, "code")
	_emailVerificationCode.ExpiresAt = field.NewTime(tableName, "expires_at")
	_emailVerificationCode.RequestType = field.NewString(tableName, "request_type")
	_emailVerificationCode.CreatedAt = field.NewTime(tableName, "created_at")

	_emailVerificationCode.fillFieldMap()

	return _emailVerificationCode
}

// emailVerificationCode Table to store email verification codes. Type: transactional
type emailVerificationCode struct {
	emailVerificationCodeDo emailVerificationCodeDo

	ALL         field.Asterisk
	ID          field.String
	UserID      field.String
	Code        field.String
	ExpiresAt   field.Time
	RequestType field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (e emailVerificationCode) Table(newTableName string) *emailVerificationCode {
	e.emailVerificationCodeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emailVerificationCode) As(alias string) *emailVerificationCode {
	e.emailVerificationCodeDo.DO = *(e.emailVerificationCodeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emailVerificationCode) updateTableName(table string) *emailVerificationCode {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewString(table, "id")
	e.UserID = field.NewString(table, "user_id")
	e.Code = field.NewString(table, "code")
	e.ExpiresAt = field.NewTime(table, "expires_at")
	e.RequestType = field.NewString(table, "request_type")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *emailVerificationCode) WithContext(ctx context.Context) IEmailVerificationCodeDo {
	return e.emailVerificationCodeDo.WithContext(ctx)
}

func (e emailVerificationCode) TableName() string { return e.emailVerificationCodeDo.TableName() }

func (e emailVerificationCode) Alias() string { return e.emailVerificationCodeDo.Alias() }

func (e emailVerificationCode) Columns(cols ...field.Expr) gen.Columns {
	return e.emailVerificationCodeDo.Columns(cols...)
}

func (e *emailVerificationCode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emailVerificationCode) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 6)
	e.fieldMap["id"] = e.ID
	e.fieldMap["user_id"] = e.UserID
	e.fieldMap["code"] = e.Code
	e.fieldMap["expires_at"] = e.ExpiresAt
	e.fieldMap["request_type"] = e.RequestType
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e emailVerificationCode) clone(db *gorm.DB) emailVerificationCode {
	e.emailVerificationCodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emailVerificationCode) replaceDB(db *gorm.DB) emailVerificationCode {
	e.emailVerificationCodeDo.ReplaceDB(db)
	return e
}

type emailVerificationCodeDo struct{ gen.DO }

type IEmailVerificationCodeDo interface {
	gen.SubQuery
	Debug() IEmailVerificationCodeDo
	WithContext(ctx context.Context) IEmailVerificationCodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEmailVerificationCodeDo
	WriteDB() IEmailVerificationCodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEmailVerificationCodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEmailVerificationCodeDo
	Not(conds ...gen.Condition) IEmailVerificationCodeDo
	Or(conds ...gen.Condition) IEmailVerificationCodeDo
	Select(conds ...field.Expr) IEmailVerificationCodeDo
	Where(conds ...gen.Condition) IEmailVerificationCodeDo
	Order(conds ...field.Expr) IEmailVerificationCodeDo
	Distinct(cols ...field.Expr) IEmailVerificationCodeDo
	Omit(cols ...field.Expr) IEmailVerificationCodeDo
	Join(table schema.Tabler, on ...field.Expr) IEmailVerificationCodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEmailVerificationCodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEmailVerificationCodeDo
	Group(cols ...field.Expr) IEmailVerificationCodeDo
	Having(conds ...gen.Condition) IEmailVerificationCodeDo
	Limit(limit int) IEmailVerificationCodeDo
	Offset(offset int) IEmailVerificationCodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEmailVerificationCodeDo
	Unscoped() IEmailVerificationCodeDo
	Create(values ...*model.EmailVerificationCode) error
	CreateInBatches(values []*model.EmailVerificationCode, batchSize int) error
	Save(values ...*model.EmailVerificationCode) error
	First() (*model.EmailVerificationCode, error)
	Take() (*model.EmailVerificationCode, error)
	Last() (*model.EmailVerificationCode, error)
	Find() ([]*model.EmailVerificationCode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmailVerificationCode, err error)
	FindInBatches(result *[]*model.EmailVerificationCode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EmailVerificationCode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEmailVerificationCodeDo
	Assign(attrs ...field.AssignExpr) IEmailVerificationCodeDo
	Joins(fields ...field.RelationField) IEmailVerificationCodeDo
	Preload(fields ...field.RelationField) IEmailVerificationCodeDo
	FirstOrInit() (*model.EmailVerificationCode, error)
	FirstOrCreate() (*model.EmailVerificationCode, error)
	FindByPage(offset int, limit int) (result []*model.EmailVerificationCode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEmailVerificationCodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e emailVerificationCodeDo) Debug() IEmailVerificationCodeDo {
	return e.withDO(e.DO.Debug())
}

func (e emailVerificationCodeDo) WithContext(ctx context.Context) IEmailVerificationCodeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emailVerificationCodeDo) ReadDB() IEmailVerificationCodeDo {
	return e.Clauses(dbresolver.Read)
}

func (e emailVerificationCodeDo) WriteDB() IEmailVerificationCodeDo {
	return e.Clauses(dbresolver.Write)
}

func (e emailVerificationCodeDo) Session(config *gorm.Session) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Session(config))
}

func (e emailVerificationCodeDo) Clauses(conds ...clause.Expression) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emailVerificationCodeDo) Returning(value interface{}, columns ...string) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emailVerificationCodeDo) Not(conds ...gen.Condition) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emailVerificationCodeDo) Or(conds ...gen.Condition) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emailVerificationCodeDo) Select(conds ...field.Expr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emailVerificationCodeDo) Where(conds ...gen.Condition) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emailVerificationCodeDo) Order(conds ...field.Expr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emailVerificationCodeDo) Distinct(cols ...field.Expr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emailVerificationCodeDo) Omit(cols ...field.Expr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emailVerificationCodeDo) Join(table schema.Tabler, on ...field.Expr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emailVerificationCodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emailVerificationCodeDo) RightJoin(table schema.Tabler, on ...field.Expr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emailVerificationCodeDo) Group(cols ...field.Expr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emailVerificationCodeDo) Having(conds ...gen.Condition) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emailVerificationCodeDo) Limit(limit int) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emailVerificationCodeDo) Offset(offset int) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emailVerificationCodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emailVerificationCodeDo) Unscoped() IEmailVerificationCodeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emailVerificationCodeDo) Create(values ...*model.EmailVerificationCode) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emailVerificationCodeDo) CreateInBatches(values []*model.EmailVerificationCode, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emailVerificationCodeDo) Save(values ...*model.EmailVerificationCode) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emailVerificationCodeDo) First() (*model.EmailVerificationCode, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerificationCode), nil
	}
}

func (e emailVerificationCodeDo) Take() (*model.EmailVerificationCode, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerificationCode), nil
	}
}

func (e emailVerificationCodeDo) Last() (*model.EmailVerificationCode, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerificationCode), nil
	}
}

func (e emailVerificationCodeDo) Find() ([]*model.EmailVerificationCode, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmailVerificationCode), err
}

func (e emailVerificationCodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmailVerificationCode, err error) {
	buf := make([]*model.EmailVerificationCode, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emailVerificationCodeDo) FindInBatches(result *[]*model.EmailVerificationCode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emailVerificationCodeDo) Attrs(attrs ...field.AssignExpr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emailVerificationCodeDo) Assign(attrs ...field.AssignExpr) IEmailVerificationCodeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emailVerificationCodeDo) Joins(fields ...field.RelationField) IEmailVerificationCodeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emailVerificationCodeDo) Preload(fields ...field.RelationField) IEmailVerificationCodeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emailVerificationCodeDo) FirstOrInit() (*model.EmailVerificationCode, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerificationCode), nil
	}
}

func (e emailVerificationCodeDo) FirstOrCreate() (*model.EmailVerificationCode, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerificationCode), nil
	}
}

func (e emailVerificationCodeDo) FindByPage(offset int, limit int) (result []*model.EmailVerificationCode, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emailVerificationCodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emailVerificationCodeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emailVerificationCodeDo) Delete(models ...*model.EmailVerificationCode) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emailVerificationCodeDo) withDO(do gen.Dao) *emailVerificationCodeDo {
	e.DO = *do.(*gen.DO)
	return e
}
