// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/UniPro-tech/UniQUE-Auth/internal/model"
)

func newExternalIdentity(db *gorm.DB, opts ...gen.DOOption) externalIdentity {
	_externalIdentity := externalIdentity{}

	_externalIdentity.externalIdentityDo.UseDB(db, opts...)
	_externalIdentity.externalIdentityDo.UseModel(&model.ExternalIdentity{})

	tableName := _externalIdentity.externalIdentityDo.TableName()
	_externalIdentity.ALL = field.NewAsterisk(tableName)
	_externalIdentity.ID = field.NewString(tableName, "id")
	_externalIdentity.UserID = field.NewString(tableName, "user_id")
	_externalIdentity.Provider = field.NewString(tableName, "provider")
	_externalIdentity.ExternalUserID = field.NewString(tableName, "external_user_id")
	_externalIdentity.IDToken = field.NewString(tableName, "id_token")
	_externalIdentity.AccessToken = field.NewString(tableName, "access_token")
	_externalIdentity.RefreshToken = field.NewString(tableName, "refresh_token")
	_externalIdentity.TokenExpiresAt = field.NewTime(tableName, "token_expires_at")
	_externalIdentity.CreatedAt = field.NewTime(tableName, "created_at")
	_externalIdentity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_externalIdentity.DeletedAt = field.NewField(tableName, "deleted_at")

	_externalIdentity.fillFieldMap()

	return _externalIdentity
}

// externalIdentity Table to store external identity links for users. Type: master
type externalIdentity struct {
	externalIdentityDo externalIdentityDo

	ALL            field.Asterisk
	ID             field.String
	UserID         field.String
	Provider       field.String
	ExternalUserID field.String
	IDToken        field.String
	AccessToken    field.String
	RefreshToken   field.String
	TokenExpiresAt field.Time
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field

	fieldMap map[string]field.Expr
}

func (e externalIdentity) Table(newTableName string) *externalIdentity {
	e.externalIdentityDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e externalIdentity) As(alias string) *externalIdentity {
	e.externalIdentityDo.DO = *(e.externalIdentityDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *externalIdentity) updateTableName(table string) *externalIdentity {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewString(table, "id")
	e.UserID = field.NewString(table, "user_id")
	e.Provider = field.NewString(table, "provider")
	e.ExternalUserID = field.NewString(table, "external_user_id")
	e.IDToken = field.NewString(table, "id_token")
	e.AccessToken = field.NewString(table, "access_token")
	e.RefreshToken = field.NewString(table, "refresh_token")
	e.TokenExpiresAt = field.NewTime(table, "token_expires_at")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.DeletedAt = field.NewField(table, "deleted_at")

	e.fillFieldMap()

	return e
}

func (e *externalIdentity) WithContext(ctx context.Context) IExternalIdentityDo {
	return e.externalIdentityDo.WithContext(ctx)
}

func (e externalIdentity) TableName() string { return e.externalIdentityDo.TableName() }

func (e externalIdentity) Alias() string { return e.externalIdentityDo.Alias() }

func (e externalIdentity) Columns(cols ...field.Expr) gen.Columns {
	return e.externalIdentityDo.Columns(cols...)
}

func (e *externalIdentity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *externalIdentity) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 11)
	e.fieldMap["id"] = e.ID
	e.fieldMap["user_id"] = e.UserID
	e.fieldMap["provider"] = e.Provider
	e.fieldMap["external_user_id"] = e.ExternalUserID
	e.fieldMap["id_token"] = e.IDToken
	e.fieldMap["access_token"] = e.AccessToken
	e.fieldMap["refresh_token"] = e.RefreshToken
	e.fieldMap["token_expires_at"] = e.TokenExpiresAt
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["deleted_at"] = e.DeletedAt
}

func (e externalIdentity) clone(db *gorm.DB) externalIdentity {
	e.externalIdentityDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e externalIdentity) replaceDB(db *gorm.DB) externalIdentity {
	e.externalIdentityDo.ReplaceDB(db)
	return e
}

type externalIdentityDo struct{ gen.DO }

type IExternalIdentityDo interface {
	gen.SubQuery
	Debug() IExternalIdentityDo
	WithContext(ctx context.Context) IExternalIdentityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IExternalIdentityDo
	WriteDB() IExternalIdentityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IExternalIdentityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IExternalIdentityDo
	Not(conds ...gen.Condition) IExternalIdentityDo
	Or(conds ...gen.Condition) IExternalIdentityDo
	Select(conds ...field.Expr) IExternalIdentityDo
	Where(conds ...gen.Condition) IExternalIdentityDo
	Order(conds ...field.Expr) IExternalIdentityDo
	Distinct(cols ...field.Expr) IExternalIdentityDo
	Omit(cols ...field.Expr) IExternalIdentityDo
	Join(table schema.Tabler, on ...field.Expr) IExternalIdentityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IExternalIdentityDo
	RightJoin(table schema.Tabler, on ...field.Expr) IExternalIdentityDo
	Group(cols ...field.Expr) IExternalIdentityDo
	Having(conds ...gen.Condition) IExternalIdentityDo
	Limit(limit int) IExternalIdentityDo
	Offset(offset int) IExternalIdentityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IExternalIdentityDo
	Unscoped() IExternalIdentityDo
	Create(values ...*model.ExternalIdentity) error
	CreateInBatches(values []*model.ExternalIdentity, batchSize int) error
	Save(values ...*model.ExternalIdentity) error
	First() (*model.ExternalIdentity, error)
	Take() (*model.ExternalIdentity, error)
	Last() (*model.ExternalIdentity, error)
	Find() ([]*model.ExternalIdentity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExternalIdentity, err error)
	FindInBatches(result *[]*model.ExternalIdentity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ExternalIdentity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IExternalIdentityDo
	Assign(attrs ...field.AssignExpr) IExternalIdentityDo
	Joins(fields ...field.RelationField) IExternalIdentityDo
	Preload(fields ...field.RelationField) IExternalIdentityDo
	FirstOrInit() (*model.ExternalIdentity, error)
	FirstOrCreate() (*model.ExternalIdentity, error)
	FindByPage(offset int, limit int) (result []*model.ExternalIdentity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IExternalIdentityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e externalIdentityDo) Debug() IExternalIdentityDo {
	return e.withDO(e.DO.Debug())
}

func (e externalIdentityDo) WithContext(ctx context.Context) IExternalIdentityDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e externalIdentityDo) ReadDB() IExternalIdentityDo {
	return e.Clauses(dbresolver.Read)
}

func (e externalIdentityDo) WriteDB() IExternalIdentityDo {
	return e.Clauses(dbresolver.Write)
}

func (e externalIdentityDo) Session(config *gorm.Session) IExternalIdentityDo {
	return e.withDO(e.DO.Session(config))
}

func (e externalIdentityDo) Clauses(conds ...clause.Expression) IExternalIdentityDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e externalIdentityDo) Returning(value interface{}, columns ...string) IExternalIdentityDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e externalIdentityDo) Not(conds ...gen.Condition) IExternalIdentityDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e externalIdentityDo) Or(conds ...gen.Condition) IExternalIdentityDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e externalIdentityDo) Select(conds ...field.Expr) IExternalIdentityDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e externalIdentityDo) Where(conds ...gen.Condition) IExternalIdentityDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e externalIdentityDo) Order(conds ...field.Expr) IExternalIdentityDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e externalIdentityDo) Distinct(cols ...field.Expr) IExternalIdentityDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e externalIdentityDo) Omit(cols ...field.Expr) IExternalIdentityDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e externalIdentityDo) Join(table schema.Tabler, on ...field.Expr) IExternalIdentityDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e externalIdentityDo) LeftJoin(table schema.Tabler, on ...field.Expr) IExternalIdentityDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e externalIdentityDo) RightJoin(table schema.Tabler, on ...field.Expr) IExternalIdentityDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e externalIdentityDo) Group(cols ...field.Expr) IExternalIdentityDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e externalIdentityDo) Having(conds ...gen.Condition) IExternalIdentityDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e externalIdentityDo) Limit(limit int) IExternalIdentityDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e externalIdentityDo) Offset(offset int) IExternalIdentityDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e externalIdentityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IExternalIdentityDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e externalIdentityDo) Unscoped() IExternalIdentityDo {
	return e.withDO(e.DO.Unscoped())
}

func (e externalIdentityDo) Create(values ...*model.ExternalIdentity) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e externalIdentityDo) CreateInBatches(values []*model.ExternalIdentity, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e externalIdentityDo) Save(values ...*model.ExternalIdentity) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e externalIdentityDo) First() (*model.ExternalIdentity, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalIdentity), nil
	}
}

func (e externalIdentityDo) Take() (*model.ExternalIdentity, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalIdentity), nil
	}
}

func (e externalIdentityDo) Last() (*model.ExternalIdentity, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalIdentity), nil
	}
}

func (e externalIdentityDo) Find() ([]*model.ExternalIdentity, error) {
	result, err := e.DO.Find()
	return result.([]*model.ExternalIdentity), err
}

func (e externalIdentityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExternalIdentity, err error) {
	buf := make([]*model.ExternalIdentity, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e externalIdentityDo) FindInBatches(result *[]*model.ExternalIdentity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e externalIdentityDo) Attrs(attrs ...field.AssignExpr) IExternalIdentityDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e externalIdentityDo) Assign(attrs ...field.AssignExpr) IExternalIdentityDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e externalIdentityDo) Joins(fields ...field.RelationField) IExternalIdentityDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e externalIdentityDo) Preload(fields ...field.RelationField) IExternalIdentityDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e externalIdentityDo) FirstOrInit() (*model.ExternalIdentity, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalIdentity), nil
	}
}

func (e externalIdentityDo) FirstOrCreate() (*model.ExternalIdentity, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExternalIdentity), nil
	}
}

func (e externalIdentityDo) FindByPage(offset int, limit int) (result []*model.ExternalIdentity, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e externalIdentityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e externalIdentityDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e externalIdentityDo) Delete(models ...*model.ExternalIdentity) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *externalIdentityDo) withDO(do gen.Dao) *externalIdentityDo {
	e.DO = *do.(*gen.DO)
	return e
}
