// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	Announcement          *announcement
	Application           *application
	AuditLog              *auditLog
	AuthorizationRequest  *authorizationRequest
	Consent               *consent
	EmailVerificationCode *emailVerificationCode
	ExternalIdentity      *externalIdentity
	OauthToken            *oauthToken
	Profile               *profile
	RedirectURI           *redirectURI
	Role                  *role
	SchemaMigration       *schemaMigration
	Session               *session
	User                  *user
	UserRole              *userRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Announcement = &Q.Announcement
	Application = &Q.Application
	AuditLog = &Q.AuditLog
	AuthorizationRequest = &Q.AuthorizationRequest
	Consent = &Q.Consent
	EmailVerificationCode = &Q.EmailVerificationCode
	ExternalIdentity = &Q.ExternalIdentity
	OauthToken = &Q.OauthToken
	Profile = &Q.Profile
	RedirectURI = &Q.RedirectURI
	Role = &Q.Role
	SchemaMigration = &Q.SchemaMigration
	Session = &Q.Session
	User = &Q.User
	UserRole = &Q.UserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Announcement:          newAnnouncement(db, opts...),
		Application:           newApplication(db, opts...),
		AuditLog:              newAuditLog(db, opts...),
		AuthorizationRequest:  newAuthorizationRequest(db, opts...),
		Consent:               newConsent(db, opts...),
		EmailVerificationCode: newEmailVerificationCode(db, opts...),
		ExternalIdentity:      newExternalIdentity(db, opts...),
		OauthToken:            newOauthToken(db, opts...),
		Profile:               newProfile(db, opts...),
		RedirectURI:           newRedirectURI(db, opts...),
		Role:                  newRole(db, opts...),
		SchemaMigration:       newSchemaMigration(db, opts...),
		Session:               newSession(db, opts...),
		User:                  newUser(db, opts...),
		UserRole:              newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Announcement          announcement
	Application           application
	AuditLog              auditLog
	AuthorizationRequest  authorizationRequest
	Consent               consent
	EmailVerificationCode emailVerificationCode
	ExternalIdentity      externalIdentity
	OauthToken            oauthToken
	Profile               profile
	RedirectURI           redirectURI
	Role                  role
	SchemaMigration       schemaMigration
	Session               session
	User                  user
	UserRole              userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Announcement:          q.Announcement.clone(db),
		Application:           q.Application.clone(db),
		AuditLog:              q.AuditLog.clone(db),
		AuthorizationRequest:  q.AuthorizationRequest.clone(db),
		Consent:               q.Consent.clone(db),
		EmailVerificationCode: q.EmailVerificationCode.clone(db),
		ExternalIdentity:      q.ExternalIdentity.clone(db),
		OauthToken:            q.OauthToken.clone(db),
		Profile:               q.Profile.clone(db),
		RedirectURI:           q.RedirectURI.clone(db),
		Role:                  q.Role.clone(db),
		SchemaMigration:       q.SchemaMigration.clone(db),
		Session:               q.Session.clone(db),
		User:                  q.User.clone(db),
		UserRole:              q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Announcement:          q.Announcement.replaceDB(db),
		Application:           q.Application.replaceDB(db),
		AuditLog:              q.AuditLog.replaceDB(db),
		AuthorizationRequest:  q.AuthorizationRequest.replaceDB(db),
		Consent:               q.Consent.replaceDB(db),
		EmailVerificationCode: q.EmailVerificationCode.replaceDB(db),
		ExternalIdentity:      q.ExternalIdentity.replaceDB(db),
		OauthToken:            q.OauthToken.replaceDB(db),
		Profile:               q.Profile.replaceDB(db),
		RedirectURI:           q.RedirectURI.replaceDB(db),
		Role:                  q.Role.replaceDB(db),
		SchemaMigration:       q.SchemaMigration.replaceDB(db),
		Session:               q.Session.replaceDB(db),
		User:                  q.User.replaceDB(db),
		UserRole:              q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	Announcement          IAnnouncementDo
	Application           IApplicationDo
	AuditLog              IAuditLogDo
	AuthorizationRequest  IAuthorizationRequestDo
	Consent               IConsentDo
	EmailVerificationCode IEmailVerificationCodeDo
	ExternalIdentity      IExternalIdentityDo
	OauthToken            IOauthTokenDo
	Profile               IProfileDo
	RedirectURI           IRedirectURIDo
	Role                  IRoleDo
	SchemaMigration       ISchemaMigrationDo
	Session               ISessionDo
	User                  IUserDo
	UserRole              IUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Announcement:          q.Announcement.WithContext(ctx),
		Application:           q.Application.WithContext(ctx),
		AuditLog:              q.AuditLog.WithContext(ctx),
		AuthorizationRequest:  q.AuthorizationRequest.WithContext(ctx),
		Consent:               q.Consent.WithContext(ctx),
		EmailVerificationCode: q.EmailVerificationCode.WithContext(ctx),
		ExternalIdentity:      q.ExternalIdentity.WithContext(ctx),
		OauthToken:            q.OauthToken.WithContext(ctx),
		Profile:               q.Profile.WithContext(ctx),
		RedirectURI:           q.RedirectURI.WithContext(ctx),
		Role:                  q.Role.WithContext(ctx),
		SchemaMigration:       q.SchemaMigration.WithContext(ctx),
		Session:               q.Session.WithContext(ctx),
		User:                  q.User.WithContext(ctx),
		UserRole:              q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
