// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/UniPro-tech/UniQUE-Auth/internal/model"
)

func newOauthToken(db *gorm.DB, opts ...gen.DOOption) oauthToken {
	_oauthToken := oauthToken{}

	_oauthToken.oauthTokenDo.UseDB(db, opts...)
	_oauthToken.oauthTokenDo.UseModel(&model.OauthToken{})

	tableName := _oauthToken.oauthTokenDo.TableName()
	_oauthToken.ALL = field.NewAsterisk(tableName)
	_oauthToken.ID = field.NewString(tableName, "id")
	_oauthToken.ConsentID = field.NewString(tableName, "consent_id")
	_oauthToken.IDTokenJti = field.NewString(tableName, "id_token_jti")
	_oauthToken.AccessTokenJti = field.NewString(tableName, "access_token_jti")
	_oauthToken.RefreshTokenJti = field.NewString(tableName, "refresh_token_jti")
	_oauthToken.ExpiresAt = field.NewTime(tableName, "expires_at")
	_oauthToken.CreatedAt = field.NewTime(tableName, "created_at")
	_oauthToken.UpdatedAt = field.NewTime(tableName, "updated_at")
	_oauthToken.DeletedAt = field.NewField(tableName, "deleted_at")

	_oauthToken.fillFieldMap()

	return _oauthToken
}

// oauthToken Table to store OAuth tokens for third-party applications. Type: master
type oauthToken struct {
	oauthTokenDo oauthTokenDo

	ALL             field.Asterisk
	ID              field.String
	ConsentID       field.String
	IDTokenJti      field.String
	AccessTokenJti  field.String
	RefreshTokenJti field.String
	ExpiresAt       field.Time
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field

	fieldMap map[string]field.Expr
}

func (o oauthToken) Table(newTableName string) *oauthToken {
	o.oauthTokenDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oauthToken) As(alias string) *oauthToken {
	o.oauthTokenDo.DO = *(o.oauthTokenDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oauthToken) updateTableName(table string) *oauthToken {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewString(table, "id")
	o.ConsentID = field.NewString(table, "consent_id")
	o.IDTokenJti = field.NewString(table, "id_token_jti")
	o.AccessTokenJti = field.NewString(table, "access_token_jti")
	o.RefreshTokenJti = field.NewString(table, "refresh_token_jti")
	o.ExpiresAt = field.NewTime(table, "expires_at")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.DeletedAt = field.NewField(table, "deleted_at")

	o.fillFieldMap()

	return o
}

func (o *oauthToken) WithContext(ctx context.Context) IOauthTokenDo {
	return o.oauthTokenDo.WithContext(ctx)
}

func (o oauthToken) TableName() string { return o.oauthTokenDo.TableName() }

func (o oauthToken) Alias() string { return o.oauthTokenDo.Alias() }

func (o oauthToken) Columns(cols ...field.Expr) gen.Columns { return o.oauthTokenDo.Columns(cols...) }

func (o *oauthToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oauthToken) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 9)
	o.fieldMap["id"] = o.ID
	o.fieldMap["consent_id"] = o.ConsentID
	o.fieldMap["id_token_jti"] = o.IDTokenJti
	o.fieldMap["access_token_jti"] = o.AccessTokenJti
	o.fieldMap["refresh_token_jti"] = o.RefreshTokenJti
	o.fieldMap["expires_at"] = o.ExpiresAt
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
}

func (o oauthToken) clone(db *gorm.DB) oauthToken {
	o.oauthTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o oauthToken) replaceDB(db *gorm.DB) oauthToken {
	o.oauthTokenDo.ReplaceDB(db)
	return o
}

type oauthTokenDo struct{ gen.DO }

type IOauthTokenDo interface {
	gen.SubQuery
	Debug() IOauthTokenDo
	WithContext(ctx context.Context) IOauthTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOauthTokenDo
	WriteDB() IOauthTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOauthTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOauthTokenDo
	Not(conds ...gen.Condition) IOauthTokenDo
	Or(conds ...gen.Condition) IOauthTokenDo
	Select(conds ...field.Expr) IOauthTokenDo
	Where(conds ...gen.Condition) IOauthTokenDo
	Order(conds ...field.Expr) IOauthTokenDo
	Distinct(cols ...field.Expr) IOauthTokenDo
	Omit(cols ...field.Expr) IOauthTokenDo
	Join(table schema.Tabler, on ...field.Expr) IOauthTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOauthTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOauthTokenDo
	Group(cols ...field.Expr) IOauthTokenDo
	Having(conds ...gen.Condition) IOauthTokenDo
	Limit(limit int) IOauthTokenDo
	Offset(offset int) IOauthTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOauthTokenDo
	Unscoped() IOauthTokenDo
	Create(values ...*model.OauthToken) error
	CreateInBatches(values []*model.OauthToken, batchSize int) error
	Save(values ...*model.OauthToken) error
	First() (*model.OauthToken, error)
	Take() (*model.OauthToken, error)
	Last() (*model.OauthToken, error)
	Find() ([]*model.OauthToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OauthToken, err error)
	FindInBatches(result *[]*model.OauthToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OauthToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOauthTokenDo
	Assign(attrs ...field.AssignExpr) IOauthTokenDo
	Joins(fields ...field.RelationField) IOauthTokenDo
	Preload(fields ...field.RelationField) IOauthTokenDo
	FirstOrInit() (*model.OauthToken, error)
	FirstOrCreate() (*model.OauthToken, error)
	FindByPage(offset int, limit int) (result []*model.OauthToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOauthTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o oauthTokenDo) Debug() IOauthTokenDo {
	return o.withDO(o.DO.Debug())
}

func (o oauthTokenDo) WithContext(ctx context.Context) IOauthTokenDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oauthTokenDo) ReadDB() IOauthTokenDo {
	return o.Clauses(dbresolver.Read)
}

func (o oauthTokenDo) WriteDB() IOauthTokenDo {
	return o.Clauses(dbresolver.Write)
}

func (o oauthTokenDo) Session(config *gorm.Session) IOauthTokenDo {
	return o.withDO(o.DO.Session(config))
}

func (o oauthTokenDo) Clauses(conds ...clause.Expression) IOauthTokenDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oauthTokenDo) Returning(value interface{}, columns ...string) IOauthTokenDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oauthTokenDo) Not(conds ...gen.Condition) IOauthTokenDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oauthTokenDo) Or(conds ...gen.Condition) IOauthTokenDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oauthTokenDo) Select(conds ...field.Expr) IOauthTokenDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oauthTokenDo) Where(conds ...gen.Condition) IOauthTokenDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oauthTokenDo) Order(conds ...field.Expr) IOauthTokenDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oauthTokenDo) Distinct(cols ...field.Expr) IOauthTokenDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oauthTokenDo) Omit(cols ...field.Expr) IOauthTokenDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oauthTokenDo) Join(table schema.Tabler, on ...field.Expr) IOauthTokenDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oauthTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOauthTokenDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oauthTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IOauthTokenDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oauthTokenDo) Group(cols ...field.Expr) IOauthTokenDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oauthTokenDo) Having(conds ...gen.Condition) IOauthTokenDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oauthTokenDo) Limit(limit int) IOauthTokenDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oauthTokenDo) Offset(offset int) IOauthTokenDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oauthTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOauthTokenDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oauthTokenDo) Unscoped() IOauthTokenDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oauthTokenDo) Create(values ...*model.OauthToken) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oauthTokenDo) CreateInBatches(values []*model.OauthToken, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oauthTokenDo) Save(values ...*model.OauthToken) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oauthTokenDo) First() (*model.OauthToken, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthToken), nil
	}
}

func (o oauthTokenDo) Take() (*model.OauthToken, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthToken), nil
	}
}

func (o oauthTokenDo) Last() (*model.OauthToken, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthToken), nil
	}
}

func (o oauthTokenDo) Find() ([]*model.OauthToken, error) {
	result, err := o.DO.Find()
	return result.([]*model.OauthToken), err
}

func (o oauthTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OauthToken, err error) {
	buf := make([]*model.OauthToken, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oauthTokenDo) FindInBatches(result *[]*model.OauthToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oauthTokenDo) Attrs(attrs ...field.AssignExpr) IOauthTokenDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oauthTokenDo) Assign(attrs ...field.AssignExpr) IOauthTokenDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oauthTokenDo) Joins(fields ...field.RelationField) IOauthTokenDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oauthTokenDo) Preload(fields ...field.RelationField) IOauthTokenDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oauthTokenDo) FirstOrInit() (*model.OauthToken, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthToken), nil
	}
}

func (o oauthTokenDo) FirstOrCreate() (*model.OauthToken, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthToken), nil
	}
}

func (o oauthTokenDo) FindByPage(offset int, limit int) (result []*model.OauthToken, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oauthTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oauthTokenDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oauthTokenDo) Delete(models ...*model.OauthToken) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oauthTokenDo) withDO(do gen.Dao) *oauthTokenDo {
	o.DO = *do.(*gen.DO)
	return o
}
